language: dart

jobs:
  include:
    - name: VM Tests
      dart: stable
      env: PLATFORM=vm

script:
  - dart pub run test -p $PLATFORM --coverage="./coverage"
  - dart pub global activate coverage
  - format_coverage -l -i ./ -o lcov.info --packages=.packages --report-on=lib
  - bash <(curl -s https://codecov.io/bash)